<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pengadaan_spk_model extends CI_Model
{

    public $table = 't_pengadaan_spk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->where('isdelete', '0');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get('v_pengadaan_spk')->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_pengadaan_spk')->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('periode', $q);
        $this->db->or_like('tanggal_kontrak', $q);
        $this->db->or_like('no_kontrak', $q);
        $this->db->or_like('tanggal_ba', $q);
        $this->db->or_like('no_ba', $q);
        $this->db->or_like('nama_unit_peruntukan', $q);
        $this->db->or_like('nama_perusahaan', $q);
        $this->db->from('v_pengadaan_spk');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('periode', $q);
        $this->db->or_like('tanggal_kontrak', $q);
        $this->db->or_like('no_kontrak', $q);
        $this->db->or_like('tanggal_ba', $q);
        $this->db->or_like('no_ba', $q);
        $this->db->or_like('nama_unit_peruntukan', $q);
        $this->db->or_like('nama_perusahaan', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get('v_pengadaan_spk')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $data = array(
            'updated_by' => $this->session->userdata('full_name'),
            'updated_date' => date('Y-m-d H:i:s'),
            'isdelete' => 1,
        );
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    ////////////////////////////////////////////////////////////////////////////////
    //SPK detail//
    ///////////////////////////////////////////////////////////////////////////////
    function get_all_detail($id)
    {
        $this->db->where('isdelete', '0');
        $this->db->order_by('id_spk', $id);
        return $this->db->get('t_pengadaan_spk_detail')->result();
    }
    // insert data
    function insert_detail($data)
    {
        $this->db->insert('t_pengadaan_spk_detail', $data);
    }
    // get data by id
    function get_by_id_detail($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('t_pengadaan_spk_detail')->row();
    }

    // update data
    function update_detail($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update('t_pengadaan_spk_detail', $data);
    }

    // delete data
    function delete_detail($id)
    {
        $data = array(
            'updated_by' => $this->session->userdata('full_name'),
            'updated_date' => date('Y-m-d H:i:s'),
            'isdelete' => 1,
        );
        $this->db->where($this->id, $id);
        $this->db->update('t_pengadaan_spk_detail', $data);
    }
}

/* End of file T_pengadaan_spk_model.php */
/* Location: ./application/models/T_pengadaan_spk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-27 14:05:47 */
/* http://harviacode.com */