<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_rkpbmd_modelx extends CI_Model
{

    public $table = 't_rkpbmd';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_parent', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('kode_unit', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('jumlah_barang', $q);
	$this->db->or_like('satuan_barang', $q);
	$this->db->or_like('status_barang', $q);
	$this->db->or_like('kondisi_barang_b', $q);
	$this->db->or_like('kondisi_barang_rr', $q);
	$this->db->or_like('kondisi_barang_rb', $q);
	$this->db->or_like('nama_peliharaan', $q);
	$this->db->or_like('semula_jumlah', $q);
	$this->db->or_like('semula_satuan', $q);
	$this->db->or_like('menjadi_jumlah', $q);
	$this->db->or_like('menjadi_satuan', $q);
	$this->db->or_like('alasan_perubahan', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdelete', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_parent', $q);
	$this->db->or_like('level', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('kode_unit', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('jumlah_barang', $q);
	$this->db->or_like('satuan_barang', $q);
	$this->db->or_like('status_barang', $q);
	$this->db->or_like('kondisi_barang_b', $q);
	$this->db->or_like('kondisi_barang_rr', $q);
	$this->db->or_like('kondisi_barang_rb', $q);
	$this->db->or_like('nama_peliharaan', $q);
	$this->db->or_like('semula_jumlah', $q);
	$this->db->or_like('semula_satuan', $q);
	$this->db->or_like('menjadi_jumlah', $q);
	$this->db->or_like('menjadi_satuan', $q);
	$this->db->or_like('alasan_perubahan', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('updated_by', $q);
	$this->db->or_like('updated_date', $q);
	$this->db->or_like('isdelete', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_rkpbmd_modelx.php */
/* Location: ./application/models/T_rkpbmd_modelx.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-31 15:01:14 */
/* http://harviacode.com */