<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_rkpbmd_model extends CI_Model
{

    public $table = 't_rkpbmd';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($tahun, $kode_unit)
    {
        $this->db->where('kode_unit', $kode_unit);
        $this->db->where('tahun', $tahun);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_parent', $q);
        $this->db->or_like('level', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('kode_unit', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('kode_barang', $q);
        $this->db->or_like('nama_barang', $q);
        $this->db->or_like('semula_jumlah', $q);
        $this->db->or_like('semula_satuan', $q);
        $this->db->or_like('menjadi_jumlah', $q);
        $this->db->or_like('menjadi_satuan', $q);
        $this->db->or_like('alasan_perubahan', $q);
        $this->db->or_like('km_jumlah', $q);
        $this->db->or_like('km_satuan', $q);
        $this->db->or_like('optim_kode_barang', $q);
        $this->db->or_like('optim_nama_barang', $q);
        $this->db->or_like('optim_jumlah', $q);
        $this->db->or_like('optim_satuan', $q);
        $this->db->or_like('riil_jumlah', $q);
        $this->db->or_like('riil_satuan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('isdelete', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, 'ASC');
        $this->db->like('id', $q);
        $this->db->or_like('id_parent', $q);
        $this->db->or_like('level', $q);
        $this->db->or_like('tahun', $q);
        $this->db->or_like('kode_unit', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('kode_barang', $q);
        $this->db->or_like('nama_barang', $q);
        $this->db->or_like('semula_jumlah', $q);
        $this->db->or_like('semula_satuan', $q);
        $this->db->or_like('menjadi_jumlah', $q);
        $this->db->or_like('menjadi_satuan', $q);
        $this->db->or_like('alasan_perubahan', $q);
        $this->db->or_like('km_jumlah', $q);
        $this->db->or_like('km_satuan', $q);
        $this->db->or_like('optim_kode_barang', $q);
        $this->db->or_like('optim_nama_barang', $q);
        $this->db->or_like('optim_jumlah', $q);
        $this->db->or_like('optim_satuan', $q);
        $this->db->or_like('riil_jumlah', $q);
        $this->db->or_like('riil_satuan', $q);
        $this->db->or_like('created_by', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('updated_by', $q);
        $this->db->or_like('updated_date', $q);
        $this->db->or_like('isdelete', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $data = array(
            'updated_by' => $this->session->userdata('full_name'),
            'updated_date' => date('Y-m-d H:i:s'),
            'isdelete' => 1,
        );
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
}

/* End of file T_rkbmd_model.php */
/* Location: ./application/models/T_rkbmd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-23 16:51:43 */
/* http://harviacode.com */