<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class T_stock_opname_model extends CI_Model
{

	public $table = 't_stock_opname';
	public $id = 'id';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL)
	{
		$this->db->like('id', $q);
		$this->db->or_like('kode_jenis_barang', $q);
		$this->db->or_like('tahun', $q);
		$this->db->or_like('tanggal_so', $q);
		$this->db->or_like('no_so', $q);
		$this->db->or_like('kode_kabupaten', $q);
		$this->db->or_like('kode_unit', $q);
		$this->db->or_like('barang', $q);
		$this->db->or_like('satuan', $q);
		$this->db->or_like('saldo_awal', $q);
		$this->db->or_like('tanggal_awal', $q);
		$this->db->or_like('jumlah_penerimaan_1', $q);
		$this->db->or_like('jumlah_penerimaan_2', $q);
		$this->db->or_like('jumlah_persediaan', $q);
		$this->db->or_like('jumlah_pengeluaran', $q);
		$this->db->or_like('saldo_adm', $q);
		$this->db->or_like('saldo_fisik', $q);
		$this->db->or_like('harga_satuan', $q);
		$this->db->or_like('nilai_persediaan', $q);
		$this->db->or_like('selisih_unit', $q);
		$this->db->or_like('selisih_rupiah', $q);
		$this->db->or_like('created_by', $q);
		$this->db->or_like('created_date', $q);
		$this->db->or_like('updated_by', $q);
		$this->db->or_like('updated_date', $q);
		$this->db->or_like('isdelete', $q);
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->like('id', $q);
		$this->db->or_like('kode_jenis_barang', $q);
		$this->db->or_like('tahun', $q);
		$this->db->or_like('tanggal_so', $q);
		$this->db->or_like('no_so', $q);
		$this->db->or_like('kode_kabupaten', $q);
		$this->db->or_like('kode_unit', $q);
		$this->db->or_like('barang', $q);
		$this->db->or_like('satuan', $q);
		$this->db->or_like('saldo_awal', $q);
		$this->db->or_like('tanggal_awal', $q);
		$this->db->or_like('jumlah_penerimaan_1', $q);
		$this->db->or_like('jumlah_penerimaan_2', $q);
		$this->db->or_like('jumlah_persediaan', $q);
		$this->db->or_like('jumlah_pengeluaran', $q);
		$this->db->or_like('saldo_adm', $q);
		$this->db->or_like('saldo_fisik', $q);
		$this->db->or_like('harga_satuan', $q);
		$this->db->or_like('nilai_persediaan', $q);
		$this->db->or_like('selisih_unit', $q);
		$this->db->or_like('selisih_rupiah', $q);
		$this->db->or_like('created_by', $q);
		$this->db->or_like('created_date', $q);
		$this->db->or_like('updated_by', $q);
		$this->db->or_like('updated_date', $q);
		$this->db->or_like('isdelete', $q);
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$data = array(
			'updated_by' => $this->session->userdata('full_name'),
			'updated_date' => date('Y-m-d H:i:s'),
			'isdelete' => 1,
		);
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}
}

/* End of file T_stock_opname_model.php */
/* Location: ./application/models/T_stock_opname_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-20 16:11:34 */
/* http://harviacode.com */